csvPaths:
  stateWiseViolence: "output/state-wise-violence"
  yearWiseViolence: "output/crimes-by-year"
  gunTypes: "output/gun-types"
  stateGenderWise: "output/state-gender-wise-counts"
  stateAgeWise: "output/state-age-wise-counts"